[package]
name = "Rust-High"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.27"
markup5ever_rcdom = "0.3.0"
delegate = "0.13.1"